<div class="news">
<?php 

	function time_elapsed_string($ptime)
	{
	    $etime = time() - $ptime;
	
	    if ($etime < 1)
	    {
	        return '0 seconds';
	    }
	
	    $a = array( 12 * 30 * 24 * 60 * 60  =>  'year',
	                30 * 24 * 60 * 60       =>  'month',
	                24 * 60 * 60            =>  'day',
	                60 * 60                 =>  'hour',
	                60                      =>  'minute',
	                1                       =>  'second'
	                );
	
	    foreach ($a as $secs => $str)
	    {
	        $d = $etime / $secs;
	        if ($d >= 1)
	        {
	            $r = round($d);
	            return $r . ' ' . $str . ($r > 1 ? 's' : '') . ' ago';
	        }
	    }
	}
	
	
	function getAuthor($author)
	{
		$startsAt = strpos($author, "(") + strlen("(");
		$endsAt = strpos($author, ")", $startsAt);
		return substr($author, $startsAt, $endsAt - $startsAt);
	}

	
	$i = 0;
	foreach($this->channel as $entry): 
?>

<h1><a href="<?php echo $entry->link(); ?>" target="_blank"><?php echo $entry->title(); ?></a></h1>
<p class="author"><em><?php echo time_elapsed_string(strtotime($entry->pubDate())); ?> | <?php echo getAuthor($entry->author()); ?></em></p>
<p><?php echo $entry->description(); ?></p>
<hr />
<?php 
	if($i >= 3){break;}
	$i++; 
	endforeach; 
?>
</div>
<p>
	<a href="http://tamuhack.blogspot.com/" title="Older entries..." target="_blank">
		<img src="<?php echo $this->baseUrl("images/index/news/more_stories.png"); ?>" id="center"/>
	</a>
</p>