<h1>News</h1>
<div class="news">
<?php 

	function time_elapsed_string($ptime)
	{
	    $etime = time() - $ptime;
	
	    if ($etime < 1)
	    {
	        return '0 seconds';
	    }
	
	    $a = array( 12 * 30 * 24 * 60 * 60  =>  'year',
	                30 * 24 * 60 * 60       =>  'month',
	                24 * 60 * 60            =>  'day',
	                60 * 60                 =>  'hour',
	                60                      =>  'minute',
	                1                       =>  'second'
	                );
	
	    foreach ($a as $secs => $str)
	    {
	        $d = $etime / $secs;
	        if ($d >= 1)
	        {
	            $r = round($d);
	            return $r . ' ' . $str . ($r > 1 ? 's' : '') . ' ago';
	        }
	    }
	}
	
	
	function getAuthor($author)
	{
		$startsAt = strpos($author, "(") + strlen("(");
		$endsAt = strpos($author, ")", $startsAt);
		return substr($author, $startsAt, $endsAt - $startsAt);
	}
	
	function getSnippet($article, $length = 700)
	{
		if (strlen($article) > $length) 
		{
			$block = 0;
			for($i = 0; $i < $length; $i++)
			{
				if(substr($article, $i, 1) == '<')
					$block = 1;
				
				if(substr($article, $i, 2) == '</')
					$block = 2;
				
				if(substr($article, $i, 1) == '>' && $block == 2)
					$block = 0;
				
				if($i+1 == $length && $block == 1)
					$length++;
			}
			
			
			return substr($article, 0, $length-1);
		}
		return $article;
		
	}

	
	$i = 0;
	foreach($this->channel as $entry): 
?>

<h1><a href="<?php echo $entry->link(); ?>" target="_blank"><?php echo $entry->title(); ?></a></h1>
<p class="author"><em><?php echo time_elapsed_string(strtotime($entry->pubDate())); ?> | <?php echo getAuthor($entry->author()); ?></em></p>
<?php //echo getSnippet($entry->description()); ?>
<?php 
	endforeach; 
?>
<hr />
</div>
<p>
	<a href="http://tamuhack.blogspot.com/" title="Older entries..." target="_blank">
		<img src="<?php echo $this->baseUrl("images/index/news/more_stories.png"); ?>" id="center"/>
	</a>
</p>