<li class="page_item page-item-2"><a href="<?php echo $this->baseUrl("controlpanel/index/"); ?>" title="Control panel home">Home</a></li>
<li class="page_item page-item-2"><a href="<?php echo $this->baseUrl("controlpanel/paybill/"); ?>" title="Pay yuor hosting bill">Pay Bill</a></li>
<li class="page_item page-item-2"><a href="<?php echo $this->baseUrl("index/loggedout/"); ?>" title="log out of your account">Log Out</a></li>
