<body>
	<h1>Welcome to TAMUHack!</h1>
	<p>Howdy <?php echo $this->name; ?>!</p>
	<p>We are thrilled that you are interested in attending a hackathon hosted in the heart of Aggieland! Click the activation link below.</p>
	<p><a href="http://tamuhack.com<?php echo $this->baseUrl("/registerext/activate/email/".$this->email."/activation/".$this->activation); ?>"><h3>Activate Here</h3></a></p>
	<p>-TMAUHack</p>
	<p>If the activation link does not work, please copy and paste this link to your browser: 
	http://tamuhack.com<?php echo $this->baseUrl("/registerext/activate/email/".$this->email."/activation/".$this->activation); ?></p>
</body>