<body>
	<h1>Welcome to tamuHack!</h1>
	<p>Howdy <?php echo $this->name; ?>!</p>
	<p>We are thrilled that you are interested in attending hackathons with us!
	There is only one more step to join the tamuHack site. Click the activation link below.</p>
	<p><a href="<?php echo $this->baseUrl("/register/activate/email/".$this->email."/activation/".$this->activation); ?>"><h3>Activate Here</h3></a></p>
	<p>-tamuHack</p>
	<p>If the activation link does not work, please copy and paste this link to your browser: <?php echo $this->baseUrl("/register/activate/email/".$this->email."/activation/".$this->activation); ?></p>
</body>