<body>
	<h1>Recover TAMUHack password</h1>
	<p>Howdy!</p>
	<p>Click the link below to reset your password.</p>
	<a href="http://tamuhack.com<?php echo $this->baseUrl("/registerext/setpass/email/".$this->email."/activation/".$this->activation); ?>"><h3>Reset Here</h3></a>
	<p>-TAMUHack</p>
	<p>Link not working? Copy and paste this link into your browser: 
	http://tamuhack.com<?php echo $this->baseUrl("/registerext/setpass/email/".$this->email."/activation/".$this->activation); ?></p>
</body>