<?php if(isset($this->wifi)) : ?>
<h1>This will only be displayed once!</h1>
<p>Write it down. Take a screenshot. You're our last hope.</p>
<h2>Login: <?php echo $this->wifi["user"]; ?></h2>
<h2>Password: <?php echo $this->wifi["pass"]; ?></h2>
<br><br>
<img src="<?php echo $this->baseUrl("images/org/wifi/last_hope.jpg"); ?>" id="center"/>

<?php else : ?>
<h2 class="center">Please enter the code we emailed to you.</h2>
<br>
<form class="form form_gencode" action="<?php echo $this->baseUrl("wifi/genwifi"); ?>" method="post">
	<label>
		<span>Code:</span>
		<?php if(isset($this->fields["key_error"])):?>
		<span class="error"><?php echo $this->fields["key_error"];?></span>
		<?php endif; ?>
		<input type="text" name="key" value="<?php echo $this->fields["key"];?>">
	</label>
	<br>
	<input type="submit" value="Submit">
</form>

<?php endif; ?>