<h1 class="center">Login</h1>

<?php if(isset($this->fields["error"])):?>
<p class="center">
	<span class="error"><?php echo $this->fields["error"];?></span>
</p>
<?php endif; ?>

<form class="form form_login" action="<?php echo $this->baseUrl("/login"); ?>" method="post">
	<label>
		<span>TAMU Email:</span>
		<?php if(isset($this->fields["email_error"])):?>
		<span class="error"><?php echo $this->fields["email_error"];?></span>
		<?php endif; ?>
		<input type="text" name="email" value="<?php echo $this->fields["email"];?>">
	</label>
	<label>
		<span>Password:</span>
		<?php if(isset($this->fields["password_error"])):?>
		<span class="error"><?php echo $this->fields["password_error"];?></span>
		<?php endif; ?>
		<input type="password" name="password">
	</label>
	<br>
	<input type="submit" value="Submit">
</form>
<br />
<p class="center">
	<a href="<?php echo $this->baseUrl("/register/recover"); ?>" title="recover lost password">forgot password?</a>
</p>