<!DOCTYPE html>
<html>
    <head>
        <title>TAMUHack - Fall 2014</title>
        
        <meta name="title" content="TAMUHack" />
		<meta name="author" content="TAMUHack | tamuhack.com" />
		<meta name="keywords" content="texas A&M hackathon, texas A&M hack, tamuhack, hackathon, hackathons, student organization, computer science" />
		<meta name="description" content="Est. 2014" />

		<link rel="stylesheet" href="<?php echo $this->baseUrl("/styles/hackathon/style.css"); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl("/styles/hackathon/typography.css"); ?>" type="text/css" media="screen" />
        
        <meta charset="utf-8">
        <meta name="description" content="TAMUHack - The college hackathon">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.2.1/pure-min.css">
        
		<!-- Google Tracking -->
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-51779003-1', 'tamuhack.com');
		  ga('send', 'pageview');
		</script>
		
    </head>
    <body>
		<!--  
		<div class="sidebar-frame">
            <div class="sidebar">
                <i class="fa fa-bars"></i>
                <a href="index.html" class="logo"><img src="/images/hackathon/cube.png"/></a>
                <div class="sidebar-menu">
                    <div id="home-menu"><i class="fa fa-home fa-fw"></i><span>Home</span></div>
                    <div id="faq-menu"><i class="fa fa-question fa-fw"></i><span>FAQ</span></div>
                    <div id="sponsors-menu"><i class="fa fa-thumbs-up fa-fw"></i><span>Sponsors</span></div>
                    <div id="contact-menu"><i class="fa fa-comments fa-fw"></i><span>Contact</span></div>
                </div>
            </div>
        </div>
         -->
        <div class="container">
            <div id="home" class="frame full-height home-img-bkg" data-stellar-background-ratio="0.5">
                <div class="landing">
                    <div class="landing-inner">
                        <img src="/images/hackathon/tamuhack_logo.png">
                        <h1 class="main-header">Texas A&M's Largest Hackathon</h1>
                        <a class="btn inner-btn first-btn" href="http://...">Apply</a>
                        <a class="btn inner-btn sec-btn" href="http://...">Sponsor</a>
                    </div>
                </div>
            </div>
         
            
            <div id="faq" class="frame faq-frame">
                <div class="header-bkg green-bkg">
                    <h1>FAQ</h1>
                    <h3>Stuff you might need to know</h3>
                </div>
                <div class="sub-frame">
                    <h2>What is TAMUHack?</h2>
                    <p>some stuff...</p>
                </div>
            </div>
           
            <div id="sponsors" class="frame">
                <div class="header-bkg grey-bkg">
                    <h1 class="sponsors">SPONSORS</h1>
                    <h3 class="sponsors">The companies that make this possible</h3>
                </div>
                <div class="sub-frame">
                    <p>If you're interested in sponsoring TAMUHack, then take a look at our (something about sponsors)</p>
                </div>
            </div>
          
        </div>
      
    </body>
</html>