<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head profile="http://gmpg.org/xfn/11">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	
	<title>TAMUHack</title>
	
	<meta name="title" content="TAMUHack" />
	<meta name="author" content="TAMUHack | tamuhack.com" />
	<meta name="keywords" content="texas A&M hackathon, texas A&M hack, tamuhack, hackathon, hackathons, student organization, computer science" />
	<meta name="description" content="Est. 2014" />

	<link rel="stylesheet" href="<?php echo $this->baseUrl("/styles/org/style.css"); ?>" type="text/css" media="screen" />
	
	<!-- jQuery library (served from Google) -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<!-- bxSlider Javascript file -->
	<script src="/js/jquery.bxslider.js"></script>
	<!-- bxSlider CSS file -->
	<link href="/styles/org/jquery.bxslider.css" rel="stylesheet" />

	<!-- WYSIWYG Editor -->
	<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
	<script type="text/javascript">
	tinymce.init({
	    selector: "textarea",
	    height : <?php echo $this->tinymceHeight; ?>,
	    menubar : false,
	    plugins: "link",
	    link_title: true,
	    charLimit : <?php echo $this->tinymceCharLimit; ?>,
	    setup: function(editor) {
	        editor.on('change', function(e) {
	            //define local variables
	            var tinymax, tinylen, htmlcount;
	            //setting our max character limit
	            tinymax = this.settings.charLimit;
	            //grabbing the length of the curent editors content
	            tinylen = this.getContent().length;
	            if (tinylen > tinymax) {
	                alert("You are limited to only 500 characters in your previous hackathon experience.");
	            }
	        });
	    }
	 });
	</script>
	
	<script type="text/javascript">
		$(document).ready(function(){
			$('.bxslider').bxSlider({
				auto:true
			});
		});
	</script>
	
	<!-- Google Tracking -->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	  ga('create', 'UA-51779003-1', 'tamuhack.com');
	  ga('send', 'pageview');
	</script>
	
</head>
		
<body> 	
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=313687308665030&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
 
 
<div class="top_nav">
    <div class="top_nav_inner">
    	<!-- Logo -->
        <a href="<?php echo $this->baseUrl("org"); ?>"><div class="top_nav_menu_logo"></div></a>
        
        <!-- Login/Register/Portal Links -->
        <div class="top_nav_login">
        	<?php if(isset($this->auth)): ?>
        	<a href="<?php echo $this->baseUrl("/portal"); ?>"><?php echo $this->auth->name; ?></a> | 
        	<a href="<?php echo $this->baseUrl("/logout"); ?>">Logout</a>
        	<?php endif; ?>
        	
        	<?php if(!isset($this->auth)): ?>
        	<a href="<?php echo $this->baseUrl("/login"); ?>">Login</a> | 
        	<a href="<?php echo $this->baseUrl("/register"); ?>">Register</a>
        	<?php endif; ?>
        </div>
        
        <!-- Primary nav menu -->
        <ul class="top_nav_menu">
        	<?php 
        		$uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); 
        		
        		/**
					below
					-to define a linked controller address, insert an array element in the form,
						array("controllerName/node", "LINK-TITLE")
					-to define an external address insert a link in the place of the controller and
						include "http". 
        		 */
        		$uris = array(
							array("/org", 			"HOME"), 
							array("/news",			"NEWS"),
							array("/contact",	 	"CONTACT")
						);
        		foreach ($uris as $item):
        	?>
        		<li<?php if($uri === $this->baseUrl($item[0])): ?> class="current"<?php endif;?>>
        			<?php if(strpos($item[0],'http://') !== false){?>
        				<a href="<?php echo $item[0]; ?>" target="_blank" ><?php echo $item[1]; ?></a>
        			<?php }else{?>
        				<a href="<?php echo $this->baseUrl($item[0]); ?>"><?php echo $item[1]; ?></a>
        			<?php }?>
        		</li>
        	<?php endforeach; ?>

        </ul>
    </div>
</div>

<!-- Page content generated below -->
<div class="body">     

	<!-- Primary nav menu -->
	<?php if(isset($this->auth)): ?>
        
        <div class="portal_nav">
	        <ul>
	        	<?php 
        		$uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); 
        		
        		/**
					below
					-to define a linked controller address, insert an array element in the form,
						array("controllerName/node", "LINK-TITLE")
					-to define an external address insert a link in the place of the controller and
						include "http". 
        		 */
        		$portalLinks = array(
							array("/portal", 		"PORTAL")
						);

				if($this->auth->account_type >= 10)
				{
					array_push($portalLinks, array("/events", "EVENTS"));
				}
				if($this->auth->account_type >= 90)
				{
					array_push($portalLinks, array("/admin", "ADMIN"));
				}

        		foreach ($portalLinks as $item):
        	?>
        		<li<?php if($uri === $this->baseUrl($item[0])): ?> class="current"<?php endif;?>>
        			<?php if(strpos($item[0],'http://') !== false){?>
        				<a href="<?php echo $item[0]; ?>"target="_blank" ><?php echo $item[1]; ?></a>
        			<?php }else{?>
        				<a href="<?php echo $this->baseUrl($item[0]); ?>"><?php echo $item[1]; ?></a>
        			<?php }?>
        		</li>
        	<?php endforeach; ?>
	        </ul>
        </div>
	<?php endif; ?>

	<div class="content">
		<?php echo $this->layout()->content; ?>
	</div>
</div> 

<!-- Bottom Nav -->
<div class="bottom_nav">
    <div class="bottom_nav_inner">
    	<div class="bottom_nav_menu_logo"></div>
    	<ul class="bottom_nav_menu">
        	<?php 
        		//array_push($uris, 	array("index/legal",	"LEGAL")
					//		);
					
        		
        		foreach ($uris as $item):
        	?>
        		<li>
        			<a href="<?php echo $this->baseUrl($item[0]); ?>"><?php echo $item[1]; ?></a>
        		</li>
        	<?php endforeach; ?>
        </ul>
        <div class="bottom_copyright">TAMUHack&copy; <?php echo date("Y"); ?></div> 
    </div>   
</div>
 
</body> 
</html> 