<h1 class="center">2014 Student Registration</h1>
<p class="center" >Registration is open to all currently enrolled college and high school students. You must be able to provide a valid student ID to be admitted to the event.</p>
<p class="center">We will dispatch an email to you for confirmation.</p>
<p class="center">TAMU students, please register <a href="<?php echo $this->baseUrl("register"); ?>">here</a>.</p>

<form class="form form_register" action="<?php echo $this->baseUrl("/registerext"); ?>" method="post">
	<label>
		<span>*First Name:</span>
		<?php if(isset($this->fields["name_first_error"])):?>
		<span class="error"><?php echo $this->fields["name_first_error"];?></span>
		<?php endif; ?>
		<input type="text" name="name_first" value="<?php echo $this->fields["name_first"];?>">
	</label>
	<label>
		<span>*Last Name:</span>
		<?php if(isset($this->fields["name_last_error"])):?>
		<span class="error"><?php echo $this->fields["name_last_error"];?></span>
		<?php endif; ?>
		<input type="text" name="name_last" value="<?php echo $this->fields["name_last"];?>">
	</label>
	<label>
		<span>School:</span>
		<input type="text" name="school" value="<?php echo $this->fields["school"];?>">
	</label>
	<label>
		<span>Expected Graduation Year (YYYY):</span>
		<input type="text" name="grad_year" value="<?php echo $this->fields["grad_year"];?>">
	</label>
	<label>
		<span>LinkedIn (Paste Entire Link):</span>
		<input type="text" name="linkedin" value="<?php echo $this->fields["linkedin"];?>">
	</label>
	<label>
		<span>*Email:</span>
		<?php if(isset($this->fields["email_error"])):?>
		<span class="error"><?php echo $this->fields["email_error"];?></span>
		<?php endif; ?>
		<input type="text" name="email" value="<?php echo $this->fields["email"];?>">
	</label>
	<label>
		<span>*Password:</span>
		<?php if(isset($this->fields["password_error"])):?>
		<span class="error"><?php echo $this->fields["password_error"];?></span>
		<?php endif; ?>
		<input type="password" name="password">
	</label>
	<br>
	<input type="submit" value="Submit">
	<label>
		<span>(*) Required</span>
	</label>
</form>