<h1 class="center">Send New Activation Link</h1>
<p class="center">If you have already registered for the site but have not received an activation email please enter it below. We will send you a new link. If the issue persists, please check your spam folder or contact us <a href="<?php echo $this->baseUrl("contact");?>">directly</a>.</p>
<?php if(isset($this->fields["error"])):?>
<p class="center">
	<span class="error"><?php echo $this->fields["error"];?></span>
</p>
<?php endif; ?>

<form class="form form_reactivate" action="<?php echo $this->baseUrl("/reactivate"); ?>" method="post">
	<label>
		<span>Email:</span>
		<?php if(isset($this->fields["email_error"])):?>
		<span class="error"><?php echo $this->fields["email_error"];?></span>
		<?php endif; ?>
		<input type="text" name="email" value="<?php echo $this->fields["email"];?>">
	</label>
	<input type="submit" value="Submit">
</form>