<h1 class="center">Send New Activation Link</h1>
<p class="center">Please enter the email you wish to reactivate.</p>
<?php if(isset($this->fields["error"])):?>
<p class="center">
	<span class="error"><?php echo $this->fields["error"];?></span>
</p>
<?php endif; ?>

<form class="form form_reactivate" action="<?php echo $this->baseUrl("/reactivate"); ?>" method="post">
	<label>
		<span>Email:</span>
		<?php if(isset($this->fields["email_error"])):?>
		<span class="error"><?php echo $this->fields["email_error"];?></span>
		<?php endif; ?>
		<input type="text" name="email" value="<?php echo $this->fields["email"];?>">
	</label>
	<input type="submit" value="Submit">
</form>