<h1>How-To Docs</h1>

<h2>Adding a Google Maps Location To An Event</h2>
<p>
<ul>
	<li>To add a Google Maps location to an event you will first need to go 
	<a href="https://developers.google.com/maps/documentation/embed/start" target="_blank">here</a>.</li>
	<li>Search for the location in the search box.</li>
	<li>Copy the generated string between "q=" and "&key=". It should be a shorthand address with some funky looking characters in it (seen below).</li>
	<li>Paste into the location field for the event.</li>
</ul>
<span class="error">Before searching...</span><br />
<img src="<?php echo $this->baseUrl("images/index/admin/howto/gmaps_location.jpg"); ?>" /><br />
<span class="error">After searching...</span><br />
<img src="<?php echo $this->baseUrl("images/index/admin/howto/gmaps_location_added.jpg"); ?>" />
</p>

<h2>Event Banner Photo</h2>
<p>
Event banner images are 960px by 160px. And have to be PNG. They are the images displayed with each individual event. 
Once a banner has been uploaded there is no need to add it again if the event is being edited. Unless you need the change the photo of course.
</p>