<h1>Admin</h1>

<p>
	<ul>
		<li><h3><a href="<?php echo $this->baseUrl("/admin/members"); ?>" >Members</a>: List of all current members</h3></li>
		<li><h3><a href="<?php echo $this->baseUrl("/admin/applications"); ?>" >Applications</a>: List of all TAMUHack 2014 Applications</h3></li>
		<li><h3><a href="<?php echo $this->baseUrl("/admin/mailout"); ?>" >Email Members</a>: Email all current members</h3></li>
		<li><h3><a href="<?php echo $this->baseUrl("/admin/events"); ?>">Events</a>: Edit and create events</h3></li>
		<li><h3><a href="<?php echo $this->baseUrl("/admin/howto"); ?>">How-To Docs</a>: How to use some of the admin systems</h3></li>
	</ul>
</p>