<?php if(isset($this->sent)):?>
<h2 style="color:green">Email Sent!</h2>
<hr />
<?php endif; ?>
<p>Note: If you insert a link be sure to specify "http://". TAMU email system doesn't show links without it.</p>
<form method="post" action="/admin/mailout" class="form form_mailout">
	<label>
		<span>Email Subject:</span>
		<input type="text" name="subject" value="Upcoming hack...">
	</label>
	<label>
		<span>Email Body:</span>
    	<textarea name="body"><h1>Email goes here...</h1><p>Some more stuff...</p></textarea>
    </label>
    <br /><br />
    <input type="submit" value="Submit" id="center">
</form>
<p>Emails may take a moment to send.</p>