<p>
	<h2>Total Members: <?php echo sizeof($this->members); ?> </h2>
	<h2>Members:</h2>
	<table>
	<tr>
		<td style="width:150px;">First Name</td>
		<td style="width:150px;">Last Name</td>
		<td style="width:150px;">Email Verified</td>
		<td style="width:150px;">Permission Level</td>
	</tr>
	<?php foreach($this->members as $member): ?>
		<tr>
			<td><?php echo $member->name_first;?></td> 
			<td><?php echo $member->name_last;?></td>
			<td>
				<?php if($member->email_verified == 1): ?>
				Yes
				<?php else: ?>
				<span class="error">No</span>
				<?php endif; ?>
			</td>
			<td><?php echo $member->account_type;?></td>
		</tr>
	<?php endforeach; ?>
	</table>
</p>
<ul>
	<li>99 - Admin</li>
	<li>10 - TAMU Student</li>
	<li>0 - Non-TAMU Student</li>
</ul>