<?php if(!isset($this->error)): ?>
<h1>Signed Up!</h1>
<p>You are now signed up for the event. This action cannot be undone at this time. 
We count on all of our members to stick to their word on attending for accountability 
purposes. If you have an emergency keeping you from attending this event, you need to 
let us know ASAP (email support@tamuhack.com). All students that RSVP and do not attend will forfeit some 
reputation points and possibly lose out on a chance to win end of the year prizes.</p>

<h1>Notice!</h1>
<p>You will still need to RSVP with the actual event. This signup is to show the club who 
is attending an event, find teammates, and earn rep for internal prizes! </p>
<?php else: ?>
<h1>Error!</h1>
<p class="error"><?php echo $this->error; ?></p>
<?php endif; ?>