 <ul class="bxslider">
	<li>
		<a href="http://engineering.tamu.edu/news/2014/03/12/aggies-win-at-facebook-hackathon" target="_blank" title="Click for full story...">
			<img src="<?php echo $this->baseUrl("images/index/index/jbox_0.jpg"); ?>" />
		</a>
	</li>
	<li><img src="<?php echo $this->baseUrl("images/index/index/jbox_1.jpg"); ?>" /></li>
	<li>
		<a href="<?php echo $this->baseUrl("/register"); ?>" title="Click to register...">
			<img src="<?php echo $this->baseUrl("images/index/index/jbox_2.jpg"); ?>" />
		</a>
	</li>
</ul>

<!--
<?php $entry = $this->channel->current(); ?>

<div class="news">
	<h2><a href="<?php echo $entry->link(); ?>" target="_blank"><?php echo $entry->title(); ?></a></h2>
	<img src="<?php echo $this->baseUrl("images/index/news/h2_news.png"); ?>" class="h2_icon" />
	<p><em><?php echo $this->timeElapsedString(strtotime($entry->pubDate())); ?></em></p>
	<p><?php echo $entry->description(); ?></p>
</div>
-->

<h1>What is a hackathon?</h1>
<p>A hackathon (also known as a hack day, hackfest, or codefest) is an event in which computer programmers, 
	graphical artists and project managers collaborate on software projects. A hackathon can last anywhere from 
	three to forty-eight hours in length and brings together some of the best upcoming minds in the tech industry. 
	Network with some of the best companies in the tech industry and build something!</p>

<h1>Why participate in a hackathon?</h1>
<p>Hackathons provide students with opportunities to learn new software technologies, hardware and 
gain real-world programming experience outside of the classroom, and make connections with 
professionals in the field. Build something cool and present your hack! Learn, have fun, and win prizes!</p>

<h1>How does tamuHack fit in?</h1>
<p>We at tamuHack know that practical programming experience is irreplaceable, but often intimidating.
	Formal computer science classes provide a basis for programming, but many students don't know where
	to start in order to turn their innovative ideas into realities. We show students the ropes when
	it comes to source control, app development, and practical applications of coding knowledge.
	tamuHack fosters innovation by providing a mentor process that bridges the gap between the
	classroom and professional computer science community. </p>

<a href="<?php echo $this->baseUrl("/register"); ?>" title="Click to register...">
	<img src="<?php echo $this->baseUrl("images/index/index/register.png"); ?>" id="center"/>
</a>