<h3>What information do we collect?</h3>
<p>We collect information from you when you play our games. Theses tracking services can be turned off in the options menu when available.</p>
<p>When ordering, registering on our site, or signing up for a game service, as appropriate, you may be asked to enter your email, name, phone number, and other account information. You may, however, visit our site anonymously.</p>
<h3>What do we use your information for?</h3>
<p>Any of the information we collect from you may be used in one of the following ways:</p>
<p>; To improve our website<br />
(we continually strive to improve our website offerings based on the information and feedback we receive from you)</p>
<p>; To improve customer service<br />
(your information helps us to more effectively respond to your customer service requests and support needs)</p>
<p>; To administer a contest, promotion, survey or other site feature</p>
<p>; To provide sponsors and ad agencies with your contact information.</p>
<h3>How do we protect your information?</h3>
<p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. Standard encryption.</p>
<h3>Do we use cookies?</h3>
<p>We do not use cookies.</p>
<h3>Do we disclose any information to outside parties?</h3>
<p>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</p>
<h3>Third party links</h3>
<p>Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</p>
<h3>California Online Privacy Protection Act Compliance</h3>
<p>Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.</p>
<h3>Childrens Online Privacy Protection Act Compliance</h3>
<p>We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act), we do not collect any information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.</p>
<h3>Your Consent</h3>
<p>By using our site, you consent to our <a style="text-decoration: none; color: #3c3c3c;" href="http://www.freeprivacypolicy.com/" target="_blank">privacy policy</a>.</p>
<h3>Changes to our Privacy Policy</h3>
<p>If we decide to change our privacy policy, we will post those changes on this page.</p>
<h3>Contacting Us</h3>
<p>If there are any questions regarding this privacy policy you may contact us using the information below:</p>
<br />
Hoverdog Privacy<br />
1003 SAN SABA<br />
College Station, Texas 77845<br />
USA<br />
support@hoverdog.com<br />