<div class="news">
<?php 

	function time_elapsed_string($ptime)
	{
	    $etime = time() - $ptime;
	
	    if ($etime < 1)
	    {
	        return '0 seconds';
	    }
	
	    $a = array( 12 * 30 * 24 * 60 * 60  =>  'year',
	                30 * 24 * 60 * 60       =>  'month',
	                24 * 60 * 60            =>  'day',
	                60 * 60                 =>  'hour',
	                60                      =>  'minute',
	                1                       =>  'second'
	                );
	
	    foreach ($a as $secs => $str)
	    {
	        $d = $etime / $secs;
	        if ($d >= 1)
	        {
	            $r = round($d);
	            return $r . ' ' . $str . ($r > 1 ? 's' : '') . ' ago';
	        }
	    }
	}
	

	
	$i = 0;
	foreach($this->channel as $entry): 
?>

<h2><a href="<?php echo $entry->link(); ?>" target="_blank"><?php echo $entry->title(); ?></a></h2>
<img src="<?php echo $this->baseUrl("images/hoverdog/news/h2_news.png"); ?>" class="h2_icon" />
<p><em><?php echo time_elapsed_string(strtotime($entry->pubDate())); ?></em></p>
<p><?php echo $entry->description(); ?></p>
<?php 
	if($i >= 3){break;}
	$i++; 
	endforeach; 
?>
</div>
<p>
	<a href="http://hoverdog.blogspot.com/" title="Older entries..." target="_blank">
		<img src="<?php echo $this->baseUrl("images/hoverdog/news/more_stories.png"); ?>"/>
	</a>
</p>