<h1>Welcome to TAMUHack</h1>
<p>One last step to register for TAMUHack 2014 (Oct 24-25)! We need you to fill out the RSVP at the link below. 
Once you submit your resume you will be good to go. We will send out emails outlining event details as the event gets closer. 
See you there!</p>

<h1 class="center"><a href="https://tamuhack2014.typeform.com/to/Vwrfd6">sign up here</a></h1>

<img src="<?php echo $this->baseUrl("images/sponsors.jpg"); ?>" id="sponsor-pic" />