<img src="<?php echo $this->baseUrl("images/org/portal/tamuhack_banner.jpg"); ?>" />
<br /><br />
<div class="center">
	<a href="http://facebook.com/tamuhack" target="_BLANK" >
    	<img src="<?php echo $this->baseUrl("images/org/icons/fb.png"); ?>" class="icon-fade"/>
    </a>
    <a href="https://twitter.com/TAMUHack" target="_BLANK" >
    	<img src="<?php echo $this->baseUrl("images/org/icons/twitter.png"); ?>" class="icon-fade" />
    </a>
</div>
