<img src="<?php echo $this->baseUrl('images/org/resume/header.jpg');?>" style="margin-left: 15px;"/>
<div id="filelist">Your browser doesn't have Flash, Silverlight or HTML5 support.</div>
<br />
 
<div id="container" style="width: 200px;margin-left: auto ;margin-right: auto ;">
    <a id="pickfiles" href="javascript:;">[Select files (pdf only)]</a>
    <br /><br /><br />
    <a id="uploadfiles" href="javascript:;"><img src="<?php echo $this->baseUrl('images/org/resume/upload.png');?>" width="165"></a>
</div>
 
<br />
<pre id="console"  style="width: 100px;margin-left: auto ;margin-right: auto ;"></pre>
 
<img src="<?php echo $this->baseUrl('images/sponsors.jpg');?>" style="margin-left: 15px;"/>

<script type="text/javascript">
// Custom example logic
 
var uploader = new plupload.Uploader({
    runtimes : 'html5,flash,silverlight,html4',
     
    browse_button : 'pickfiles', // you can pass in id...
    container: document.getElementById('container'), // ... or DOM Element itself
     
    url : "<?php echo $this->baseUrl('resume/upload');?>",
     
    filters : {
        max_file_size : '8mb',
        mime_types: [
            {title : "PDF files", extensions : "pdf"}
        ]
    },
 
    // Flash settings
    flash_swf_url : '/plupload/js/Moxie.swf',
 
    // Silverlight settings
    silverlight_xap_url : '/plupload/js/Moxie.xap',
     
 
    init: {
        PostInit: function() {
            document.getElementById('filelist').innerHTML = '';
 
            document.getElementById('uploadfiles').onclick = function() {
                uploader.start();
                return false;
            };
        },
 
        FilesAdded: function(up, files) {
            plupload.each(files, function(file) {
                document.getElementById('filelist').innerHTML += '<div id="' + file.id + '">' + file.name + ' (' + plupload.formatSize(file.size) + ') <b></b></div>';
            });
        },
 
        UploadProgress: function(up, file) {
            document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
        },
 
        Error: function(up, err) {
            document.getElementById('console').innerHTML += "\nError #" + err.code + ": " + err.message;
        }
    }
});
 
uploader.init();
</script>
</script>