<h1>Benefits of Membership</h1>
<p>
	<ul>
		<li>Sign up for our hackathons</li>
		<li>Find teammates for hackathons</li>
		<li>Network with top tech companies</li>
		<li>Get a cool TAMUHack shirt</li>
		<li>Get a chance to win cool prizes within TAMUHack</li>
		<li>Attend TAMUHack mini-lectures on source control, API's and other technologies</li>
	</ul>
</p>
<hr />
<h1 class="center">Join Today!</h1>
<p class="center" >Open to current students of Texas A&M University (College Station)</p>
<p class="center">Please fill out the form to join, we will dispatch an email to you for confirmation. Also, 
Neo (@neo.tamu.edu) is no longer required, just use @tamu.edu.</p>

<form class="form form_register" action="<?php echo $this->baseUrl("/register"); ?>" method="post">
	<label>
		<span>*First Name:</span>
		<?php if(isset($this->fields["name_first_error"])):?>
		<span class="error"><?php echo $this->fields["name_first_error"];?></span>
		<?php endif; ?>
		<input type="text" name="name_first" value="<?php echo $this->fields["name_first"];?>">
	</label>
	<label>
		<span>*Last Name:</span>
		<?php if(isset($this->fields["name_last_error"])):?>
		<span class="error"><?php echo $this->fields["name_last_error"];?></span>
		<?php endif; ?>
		<input type="text" name="name_last" value="<?php echo $this->fields["name_last"];?>">
	</label>
	<label>
		<span>*TAMU Email:</span>
		<?php if(isset($this->fields["email_error"])):?>
		<span class="error"><?php echo $this->fields["email_error"];?></span>
		<?php endif; ?>
		<input type="text" name="email" value="<?php echo $this->fields["email"];?>">
	</label>
	<label>
		<span>*Password:</span>
		<?php if(isset($this->fields["password_error"])):?>
		<span class="error"><?php echo $this->fields["password_error"];?></span>
		<?php endif; ?>
		<input type="password" name="password">
	</label>
	<br>
	<input type="submit" value="Submit">
	<label>
		<span>(*) Required</span>
	</label>
</form>